homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 48.8278964
  longitude: 9.2673625
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 282
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:
  themes:
    slate:
      # Main colors
      primary-color: '#2980b9'
      accent-color: '#2980b9'
      dark-primary-color: 'var(--accent-color)'
      light-primary-color: 'var(--accent-color)'
      # Text colors
      primary-text-color: '#FFFFFF'
      text-primary-color: 'var(--primary-text-color)'
      secondary-text-color: '#b58e31'
      disabled-text-color: '#777777'
      label-badge-border-color: 'green'
      # Sidebar
      sidebar-icon-color: '#777777'
      # Background colors
      primary-background-color: '#222222'
      secondary-background-color: '#222222'
      divider-color: 'rgba(0, 0, 0, .12)'
      table-row-background-color: '#292929'
      table-row-alternative-background-color: '#292929'
      # Nav Menu
      paper-listbox-color: '#777777'
      paper-listbox-background-color: '#141414'
      paper-grey-50: 'var(--primary-text-color)'
      paper-grey-200: '#222222'
      # Paper card
      paper-card-header-color: 'var(--accent-color)'
      paper-card-background-color: '#292929'
      paper-dialog-background-color: '#292929'
      paper-item-icon-color: 'var(--primary-text-color)'
      paper-item-icon-active-color: '#b58e31'
      paper-item-icon_-_color: 'green'
      paper-item-selected_-_background-color: '#292929'
      paper-tabs-selection-bar-color: 'green'
      # Labels
      label-badge-red: 'var(--accent-color)'
      label-badge-text-color: 'var(--primary-text-color)'
      label-badge-background-color: '#222222'
      # Switches
      paper-toggle-button-checked-button-color: 'var(--accent-color)'
      paper-toggle-button-checked-bar-color: 'var(--accent-color)'
      paper-toggle-button-checked-ink-color: 'var(--accent-color)'
      paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'
      # Sliders
      paper-slider-knob-color: 'var(--accent-color)'
      paper-slider-knob-start-color: 'var(--accent-color)'
      paper-slider-pin-color: 'var(--accent-color)'
      paper-slider-active-color: 'var(--accent-color)'
      paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
      paper-slider-secondary-color: 'var(--secondary-background-color)'
      paper-slider-disabled-active-color: 'var(--disabled-text-color)'
      paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'
      # Google colors
      google-red-500: '#b58e31'
      google-green-500: '#2980b9'

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

vacuum:
  - platform: xiaomi_miio
    host: 192.168.0.43
    token: 31634e56746d47545365417a546c5236
